services:
  traefik:
    volumes:
      - ./traefik/local-certs:/certs
      - ./traefik/config:/config
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
    command:
      - "--configfile=/etc/traefik/traefik.yml"
      - "--log.level=DEBUG"

  backend:
    build:
      args:
        ENV: development
    deploy:
      replicas: 1
    environment:
      - ENV=development
    volumes:
      - ./apps/backend:/app
      - ./libs:/app/libs
      - /app/node_modules
    labels:
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.backend.tls.certresolver="

  frontend:
    build:
      args:
        ENV: development
    deploy:
      replicas: 1
    environment:
      - ENV=development
    volumes:
      - ./apps/frontend:/app
      - ./libs:/app/libs
      - /app/node_modules
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.frontend.tls.certresolver="