services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: backend
    ports:
      - "8080:3000" # Map host port 4001 to container's port 3000
    environment:
      NODE_ENV: production
    networks:
      - intersides-workspace-network

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: frontend
    ports:
      - "3000:3000" # Map host port 4002 to container's port 3000
    environment:
      NODE_ENV: production
    networks:
      - intersides-workspace-network

networks:
  intersides-workspace-network:
    driver: bridge
#    driver: overlay
#    attachable: true
