version: "3.8"

services:
  backend-server:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./apps/backend-server:/app
      - ./libs:/app/libs  # Ensure shared libraries are available
      - /app/node_modules  # Avoid overwriting node_modules
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]

  frontend-app:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./apps/frontend-app:/app
      - ./libs:/app/libs
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
