#log:
#  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443



certificatesResolvers:
  letsencrypt:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: http
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
