api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        domains:
          - main: "alkimia.localhost"
            sans:
              - "*.alkimia.localhost"

  traefik:
    address: :8080

log:
  level: DEBUG

tls:
  certificates:
    - certFile: "/certs/fullchain.pem"
      keyFile: "/certs/key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/fullchain.pem"
        keyFile: "/certs/key.pem"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /config
    watch: true